apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::212258970527:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-ZSJRM8E8WB6A
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
     - system:masters
      rolearn: arn:aws:iam::212258970527:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-26T10:37:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1622"
  uid: 2228a51c-9ead-42f3-849c-b94039695502
